export const RconEvents = {
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  POSSESSED_ADMIN_CAMERA: 'POSSESSED_ADMIN_CAMERA',
  UNPOSSESSED_ADMIN_CAMERA: 'UNPOSSESSED_ADMIN_CAMERA',
  PLAYER_WARNED: 'PLAYER_WARNED',
  PLAYER_KICKED: 'PLAYER_KICKED',
  PLAYER_BANNED: 'PLAYER_BANNED',
  SQUAD_CREATED: 'SQUAD_CREATED',
  LIST_PLAYERS: 'ListPlayers',
  LIST_SQUADS: 'ListSquads',
  SHOW_CURRENT_MAP: 'ShowCurrentMap',
  SHOW_NEXT_MAP: 'ShowNextMap',
  SHOW_SERVER_INFO: 'ShowServerInfo',
};
